
GET http://localhost:8090/api/warehousemanager/trucks/onSite?date=2024-10-19
Content-Type: application/json
###


GET http://localhost:8090/api/warehousemanager/trucks/onTime?date=2024-10-19
Content-Type: application/json
###
POST http://localhost:8090/api/appointments
Content-Type: application/json

{
  "sellerId": "8d50dbe3-68a4-4afc-a242-13818629ac9d",
  "licensePlate": "ABC123M",
  "materialType": "PETCOKE",
  "time": "2024-10-19T11:00:00"
}

### Weigh-In Test Request

POST http://localhost:8090/api/weighbridge/trucks/weighIn
Content-Type: application/json

{
  "licensePlate": "ABC123M",
  "startWeight": 150.0,
  "materialType": "PETCOKE",
  "sellerId": "8d50dbe3-68a4-4afc-a242-13818629ac9d",
  "weighInTime": "2024-10-19T11:00:00"
}

###
POST http://localhost:8090/api/weighbridge/trucks/weighOut
Content-Type: application/json

{
  "licensePlate": "ABC123M",
  "endWeight": 23.0,
  "materialType": "PETCOKE",
  "sellerId": "8d50dbe3-68a4-4afc-a242-13818629ac9d",
  "weighOutTime": "2024-10-19T12:00:00",
  "WeighBridgeTicketId": "f25f0647-bf2f-497f-b1a5-53ed4ae54dcf"
}



###
# get wearhouse overView with deatsil about the warehouse
GET http://localhost:8090/api/warehousemanager/warehouses
Content-Type: application/json


###


POST http://localhost:8090/api/PurchaseOrder
Content-Type: application/json

{
  "orderDate": "2024-10-19",
  "sellerId": "8d50dbe3-68a4-4afc-a242-13818629ac9d",
  "customerName": "coco",
  "materialType": "IRON",
  "amountOfMaterialInTons": 100.0
}


###


POST http://localhost:8090/api/ships
Content-Type: application/json
