#### Get access token for 'manager'
POST http://localhost:8180/realms/mineral/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=backend&username=managerali&password=ali&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token);
%}

###

POST http://localhost:8090/api/PurchaseOrders
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "orderDate": "2024-10-24",
  "sellerId": "8d50dbe3-68a4-4afc-a242-13818629ac9d",
  "customerName": "coco",
  "buyerId" : "8d50dbe3-68a4-4afc-a242-13818629ac9f",
  "orderLines" : [
    {
    "materialType": "IRON",
    "quantity": 40.0 ,
    "pricePerTon":10
  },
    {
      "materialType": "CEMENT",
      "quantity": 40.0 ,
      "pricePerTon":20
    }
    ]
}

###
GET http://localhost:8090/api/PurchaseOrders
Content-Type: application/json
Authorization: Bearer {{access_token}}
